### ISSUE TITLE
Events team meeting, March 14th

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#11]
At 4-4:30pm UTC on [Telegram](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)

* Event submission template https://github.com/rust-community/events-team/issues/8
* Activate Mozilla https://github.com/rust-community/events-team/issues/7
* Write a better README https://github.com/rust-community/events-team/issues/10
* Plan for all-hands https://github.com/rust-community/team/issues/224
* Upcoming event list

**Comment by skade** [comment]
@badboy will take over #8 and #7.

@mattgathu will take over #10 

rust-community/team#224 is a group effort.

@flaki will take over the upcoming event list and write a ticket.

**Comment by vamshi9666** [comment]
what about a community which is likely to have a conference in local city ?

**Comment by vamshi9666** [comment]
can we have any support from rust community (like swag )
