### ISSUE TITLE
Meeting agenda January 31st

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#2]
At 4-4:30pm UTC on #rust-events on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-events

Topics to cover:
* Future meeting spots and times (preferably Flaki-compatible)
* Comments on the [draft](https://github.com/rust-community/events-team/issues/1)
* Announcement?

**Comment by flaki** [comment]
> (preferably Flaki-compatible)
You know there's no such thing.. 😜

According to [logbot](https://mozilla.logbot.info/rust-events/20180130) there wasn't too much I missed at yesterday's meeting, but in general 4pm UTC on Wednesdays works well, and most of my travels happen early in the week or later towards the weekend, so Wednesdays are _"reasonably Flaki-safe" :)

**Comment by skade** [comment]
We used proper protocol: we talked and _then_ we activated the log bot.

Full log [here](https://github.com/rust-community/events-team/blob/master/log-2018-01-31.txt)
