### ISSUE TITLE
 Events team meeting, April 25th

### ISSUE THREAD

**Issue by badboy** [rust-community/events-team#24]
At 5-5:30pm UTC on [Telegram](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)
[Previous meeting](https://github.com/rust-community/events-team/issues/23)

Attendees: 

Agenda:

* Conference list
* Conference structural issues
* Swag sending problems
* Interaction with Mozilla events
* RustFest group meeting?

**Comment by skade** [comment]
Closing, has happened.
