### ISSUE TITLE
Confusion around meeting time

### ISSUE THREAD

**Issue by badboy** [rust-community/events-team#25]
There seems to be a bit of confusion regarding meeting times.

Today we did it at 16:00 UTC (18:00 UTC+2/German time).
General meeting is (now) 17:00 UTC (19:00 UTC+2/German time).

Do we also move it during Summer time?

**Comment by badboy** [comment]
cc @skade

**Comment by celaus** [comment]
Meeting time is now 6pm UTC, on Wednesdays. [What's this in my time zone](https://www.google.de/search?q=6pm+utc)
