### ISSUE TITLE
Work meeting on RustFest Sunday

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#30]
@celaus when will you leave on Sunday?

**Comment by celaus** [comment]
6pm is my flight from CDG (i.e. I will leave around 3:30/4pm)

**Comment by mattgathu** [comment]
Hi @skade I will be available for the work meeting :-)
Sorry I missed the meeting yesterday :-(

**Comment by skade** [comment]
@mattgathu Happens :). See you there, then :).

**Comment by skade** [comment]
@celaus can you please add the notes here?

**Comment by celaus** [comment]
# Notes

- Finish time line proposal
- Create a list of larger events and groups
- Conference support policy
- Public visibility upgrade: 
   - List of possible event types
   - Timeline 
   - Goals
- Find more conferences
- Impl days description
    - Move to its own event type
- Fork community pages & create events team subpage
