### ISSUE TITLE
Events team meeting, June 6th

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#32]
At 4-4:30pm UTC on [Telegram](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)
[Previous meeting](https://github.com/rust-community/events-team/issues/23)

Attendees: 

Agenda:

* Conference experiences
* Work items for June
* Continuing foss-events-planner
* moving to discord/staying at telegram?
* fixing the time

**Comment by celaus** [comment]
Meeting notes from the post-Rustfest meeting in #30

**Comment by skade** [comment]
Meeting is in the past, closing.
