### ISSUE TITLE
Event team meeting agenda 14.02.

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#4]
At 4-4:30pm UTC on [Telegram](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)

Because I might not be able to attend, @badboy is going to be your host.

Agenda:
* Finding a place to collect material (for example, the RustFest travel guides)
* Collecting topics to create checklists for (Meetup, Accessibility, etc.)
* Finding a work date to improve https://activate.mozilla.community/rust-hack/
* Task: Event submission template

**Comment by Manishearth** [comment]
If we have time:

 - Meetup consolidation and coordination

**Comment by skade** [comment]
@Manishearth does the consilidation task need an issue?

**Comment by Manishearth** [comment]
It's tracked in https://github.com/rust-community/switchboard-team/issues/2

**Comment by skade** [comment]
Perfect!
