### ISSUE TITLE
DevFest Cancun

### ISSUE THREAD

**Issue by mattdark** [rust-community/events-team#44]
# Conference

## Where

Cancún, Quintana Roo, Mexico

## What

DevFest Cancun is an event that will bring together world-class experts in technology, development and design. The event will last three days and it will offer conferences, workshops and a hackathon.The event is organized by GDG Cancun and focus on developers and designers from the software industry, companies, university students and technology enthusiasts. 

* Conference: How integrate Rust with your Python project
* Workshop: Dive Into Rust

* [ ] Learners Group
* [ ] Meetup with talks
* [x] Conference/Camp

Links: https://devfestcancun.com/

## When

November 7th - November 9th

* [x] I'd like the event to be on the public calendar
* [ ] It's a repeating event, I would like to have access to the calender to do things on my own

## Support

* [ ] I need coaching or help to get started faster
* [ ] I would like to be introduced to fellow meetup organizers in my area
* [ ] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [ ] I need additional help promoting my event

* [x] I'd like to have swag (e.g. stickers)

If you're interested in obtaining stickers and/or swag, please send a short email to [the community team](mailto:community@rust-lang.org?subject=[SWAG]), providing

- Your physical mail address and phone number
- The projected number of attendees for your event
- How many events you're planning to run in the future
- Optionally, if you're interested in a certain type of swag for specific reasons (e.g. you're running a T-Shirt give away)

**Comment by skade** [comment]
Hi @mattdark, I added the conference to the calendar as "Rust Workshop (Spanish) by Mario Garcia @ DevFest Cancun". Can you confirm that the workshop is held in Spanish?

**Comment by mattdark** [comment]
Hi @skade. Thanks. Yes, the workshop will be in Spanish

**Comment by flaki** [comment]
Hey @mattdark !
I'm closing this issue to clean up the repo, but if you have any thoughts or comments (or links/blogposts etc.) to share about how the event went we would be happy to hear about them!
