### ISSUE TITLE
Fosdem 2019 Rust devroom

### ISSUE THREAD

**Issue by ehiggs** [rust-community/events-team#46]
# FOSDEM 2019 Rust Devroom

## Where

Brussels, Belgium

## What

FOSDEM is a free event for software developers to meet, share ideas and collaborate.

Every year, thousands of developers of free and open source software from all over the world gather at the event in Brussels.

* [ ] Learners Group
* [ ] Meetup with talks
* [x] Conference/Camp

Links: 
https://fosdem.org/2019/

## When

2, 3 February 2019

* [x] I'd like the event to be on the public calendar
* [ ] It's a repeating event, I would like to have access to the calendar to do things on my own

## Support

* [ ] I need coaching or help to get started faster
* [ ] I would like to be introduced to fellow meetup organizers in my area
* [ ] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [x] I need additional help promoting my event

* [x] I'd like to have swag (e.g. stickers)

If you're interested in obtaining stickers and/or swag, please send a short email to [the community team](mailto:community@rust-lang.org?subject=[SWAG]), providing

- Your physical mail address and phone number
- The projected number of attendees for your event
- How many events you're planning to run in the future
- Optionally, if you're interested in a certain type of swag for specific reasons (e.g. you're running a T-Shirt give away)

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [x] We use a Code of Conduct: https://fosdem.org/2019/practical/conduct/
* [ ] We need a recommendation for one

## Contact details

* [x] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by ehiggs** [comment]
NB: so far we've submitted a proposal for a devroom. There has been no response yet.

**Comment by skade** [comment]
Hi,

so FOSDEM is a little bit of an oddball here, and the reasons lie in history.

1) We don't trust FOSDEMs Code of Conduct and especially their practices around them, reasons lie in an complaint back in 2015 that hasn't been properly cleared. http://skade.me/blog/2015/fosdem-2015.html
FOSDEM still maintains the stance that nothing has ever been reported there.
Note that DevRooms are allowed to have their own CoCs on FOSDEM.
2) The team organising the room last year felt like it was badly managed, @badboy can give details on that.

For the reasons laid out above, my _personal_ answer here (for years) is that I don't want to support a FOSDEM devroom and would not like to make this a Rust project thing by supporting it with the events team.

Still, I do appreciate that people see FOSDEM as a place where you need to be present (I feel like they are giving FOSDEM too much credit there, though). So if you have any questions about organising in general, feel free to approach the individual team members who have been involved.

**Comment by badboy** [comment]
As I understand this the fosdem 2018 devroom team is involved in it again (@lucab et all, please name the team in the above).
I attended this year and briefly helped out with on-site organisation/room handling for the Rust Dev Room. The Dev Room team did a great job of handling the room and the overflow of people.
However, the room was clearly too small.

If another dev room happens, I'd like to see an effective CoC and clear stances on handling it.

Same as @skade I don't want to discourage anyone from organising this.
2018 was handled without much of the community team's involvement and I think this is a decent way to move forward.
Personally I will not attend Fosdem 2019.

**Comment by ehiggs** [comment]
>The team organising the room last year felt like it was badly managed, @badboy can give details on that.

> I attended this year and briefly helped out with on-site organisation/room handling for the Rust Dev Room. The Dev Room team did a great job of handling the room and the overflow of people.
However, the room was clearly too small.

These comments don't seem to line up. @skade, was there more feedback that we didn't receive on how to run the devroom better? There's a deep pool of experience in the rust community team and if we can improve the experience for attendees, I think we're receptive of ideas.

**Comment by badboy** [comment]
I'm not 100% sure what @skade was referring to (I'll talk to him again though).
I complained about the general state of the venue and the size of rooms, but that's basically out of the hand of the dev room organizers (except from maybe trying to coordinate with fosdem about the room size? Not sure if they are up to that)

**Comment by itkovian** [comment]
@badboy I think that over the past (10) years FOSDEM has grown quite a bit. I have no idea what other venues could be used under similar conditions that would accommodate more people, barring a real conference centre, which is out of the question unless organisers start asking a (hefty) entrance fee. The ULB is a pretty "old" university site (except the K building), so that also explains the state of the venue -- which, imo, is not too shabby, but YMMV :)

My understanding is that FOSDEM tries to grant rooms based on relative expected attendance, interest and feedback from prior years. The HPC/Apache room for example moved from being in the AW building (very small rooms) to being in H in a much larger room due to the large interest it sparked. So if we keep it up for a few years, we also could get a larger room, though I think we actually had one of the larger class rooms available.

**Comment by itkovian** [comment]
Since there was no update posted here, I'd like to mention that the devroom was accepted. Again, any and all pointers that can help us do a better job running the room are appreciated.

**Comment by ehiggs** [comment]
https://fosdem.org/2019/schedule/track/rust/

**Comment by ehiggs** [comment]
Things went very well. Thanks to everyone who participated!
