### ISSUE TITLE
Remove Rust Mountain View

### ISSUE THREAD

**Issue by PrototypeNM1** [rust-community/events-team#51]
Rust Mountain View is set to automatically generate events, but it appears that these events are not guaranteed to occur as the organizers are not present - https://www.meetup.com/Rust-Dev-in-Mountain-View/discussions/6295511735992320/chat/ - though the group is not completely abandoned - https://www.meetup.com/Rust-Dev-in-Mountain-View/discussions/5723402399645696/chat/.

Until they resolve this issue they should be delisted.

**Comment by badboy** [comment]
Hey, thanks for reporting that and sorry for not answering earlier.
Looks like at least for last weekend 2 people met. However, I still removed the calendar entry for now and I'm trying to get into contact with the organizer to see if there's any drive behind to keep it alive.

**Comment by PrototypeNM1** [comment]
Thanks for the follow up. I reached out to the event coordinator when I opened this issue so that they could contest it and haven't heard back via meetup or this issue. I'll attend the next meetup and report back what the situation is.

**Comment by PrototypeNM1** [comment]
Verified with the other individual who attended the last meetup that the organizer has not been in attendance, but the other individual intended to continue meeting regularly regardless. If you hear back from the organizer it might make sense to see if the two of them would be interested in transferring maintainership of the event.
