### ISSUE TITLE
Rust MX meetup

### ISSUE THREAD

**Issue by mayela** [rust-community/events-team#52]
***Please help us by filling out the text below. All answers are optional***

# New Meetup

## Where
Mexico City

*The location you are running things in*

## What

We meet us in an office and talk about Rust and the tools made by it.

* [ ] Learners Group
* [x ] Meetup with talks
* [ ] Conference/Camp

Links: https://www.meetup.com/es/Rust-MX/

## When

The 3rd Wednesday of each month

* [ ] I'd like the event to be on the public calendar
* [x ] It's a repeating event, I would like to have access to the calender to do things on my own

## Support

* [ ] I need coaching or help to get started faster
* [ ] I would like to be introduced to fellow meetup organizers in my area
* [ x] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [ ] I need additional help promoting my event

* [x] I'd like to have swag (e.g. stickers)

If you're interested in obtaining stickers and/or swag, please send a short email to [the community team](mailto:community@rust-lang.org?subject=[SWAG]), providing

- Your physical mail address and phone number
- The projected number of attendees for your event
- How many events you're planning to run in the future
- Optionally, if you're interested in a certain type of swag for specific reasons (e.g. you're running a T-Shirt give away)

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [x] We use a Code of Conduct
* [ ] We need a recommendation for one

## Contact details

* [x] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by badboy** [comment]
Hi @mayela. Sorry for not replying to you faster.
I know it's now a bit on short notice, but I still added the upcoming event to the Rust community calendar. 
If you plan to have events in the future I can give you access to the calendar. For that please write an email to community@rust-lang.org and include a google-connected email address to use for access.

**Comment by flaki** [comment]
Hey @mayela !
I'm closing this issue to clean up the repo, but if you have any thoughts or comments (or links/blogposts etc.) to share about how the event went we would be happy to hear about them!
