### ISSUE TITLE
Rust room on FOSS North community day (April 7th)

### ISSUE THREAD

**Issue by skade** [rust-community/events-team#53]
The organisers of FOSS North have approached us about the prospect of running a room on their community day on April 7th.

As we have community members and an active usergroup in Gothenburg, this sounds like a good match.

For that, we need to clarify:
* What would be the exact program the devroom runs?
  * Shall we prepare issues?
* Where to host it (FOSS North is able to cover that)
* How to advertise it
* Whether or not to fly in additional community members to train them
* What is the amount of support the events team can give there?

**Comment by skade** [comment]
I created a document for writing an announcement text https://hackmd.io/rE1DVzGPS3GIJP3YTQ7kMQ?edit

**Comment by badboy** [comment]
https://foss-north.se/2019/
in Gothenburg, Sweden
April 7: Community Day
April 8-9: Conference
April 10: Training Day

**Comment by skade** [comment]
If we're thinking about a hack space, it might be worthwhile to create a signup form and check for the crowd of people actually registering interest and tailor to them.

**Comment by skade** [comment]
I added some text to the hackmd. It would be great if someone created a form.

**Comment by faern** [comment]
I created a Google form and added to the hackmd.

**Comment by skade** [comment]
@faern  looks good :). Do you want to send the text out?

**Comment by faern** [comment]
Done. I emailed it to the organizers.

**Comment by faern** [comment]
The event is now done. There were approximately 20 people there. Everyone asked relevant questions and seemed to enjoy the experience :) I think this can be closed now.

**Comment by badboy** [comment]
Thanks, @faern! Happy it worked out in the end.
