### ISSUE TITLE
Rust London meetup

### ISSUE THREAD

**Issue by xd009642** [rust-community/events-team#55]
Just wondering if there's any plans to get the Rust London meetups going again? I've not organised one before but am willing to help if needed (though I'm unavailable for like half of March). CC @booyaa

**Comment by flaki** [comment]
Sorry for not getting back to you earlier on this @xd009642, but for posterity's sake: the [Rust London User Group](https://www.meetup.com/Rust-London-User-Group) has now both regular Talk-y meetups and a new Study Group.

I'm closing this issue to clean up the repo, but if you have any thoughts or comments feel free to share them below
