### ISSUE TITLE
rust-lang Wales

### ISSUE THREAD

**Issue by 06kellyjac** [rust-community/events-team#56]
# New Meetup

## Where

Cardiff, Wales, UK
Further details on specific location to come.

## What

A meetup for anyone interested in rust.

* [X] Learners Group
* [X] Meetup with talks
* ~Conference/Camp~

The goal is for it to be a Meetup with talks but we expect there aren't many people already proficient in Rust in the area so it'll naturally be very beginner/learner focused to start off.

Links:
Website: <https://rust-lang.wales>
Twitter: [@rustlang_wales](https://twitter.com/rustlang_wales)
Meetup.com: To come

## When

The first event will be 15th May to celebrate 4 years since Rust 1.0.0

* [X] I'd like the event to be on the public calendar
* [X] It's a repeating event, I would like to have access to the calendar to do things on my own

While we hope for this event to be repeating we need to see the turnout of the first and second events.  
With a sensible estimate we expect meetups outside of special occasions to be quite a lot smaller and end up being hack sessions until the language becomes more popular in the area.

## Support

* I need coaching or help to get started faster
* ~I would like to be introduced to fellow meetup organizers in my area~
* [X] I need help promoting

There is quite a lot of support for meetups in Cardiff so coaching would be welcome but not essential.

* [X] I need additional help promoting my event

* [X] I'd like to have swag (e.g. stickers)
  * [ ] Have sent an email

If you're interested in obtaining stickers and/or swag, please send a short email to [the community team](mailto:community@rust-lang.org?subject=[SWAG]), providing

- Your physical mail address and phone number
- The projected number of attendees for your event
- How many events you're planning to run in the future
- Optionally, if you're interested in a certain type of swag for specific reasons (e.g. you're running a T-Shirt give away)

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [X] We use a Code of Conduct
* ~We need a recommendation for one~

We will (probably) just use the rust-lang one.

## Contact details

* [ ] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by flaki** [comment]
Hey @06kellyjac !
I'm closing this issue to clean up the repo, but if you have any thoughts or comments (or links/blogposts etc.) to share about how the event went we would be happy to hear about them!
