### ISSUE TITLE
Rust Port harcourt 

### ISSUE THREAD

**Issue by jamessandy** [rust-community/events-team#58]
***Please help us by filling out the text below. All answers are optional***

# From Dust to Rust

## Tech Creek

*The location you are running things in*

## What

*This event will feature workshops and talk on getting off with rust*

 

Links: *add links, e.g. a meetup page, here*

## When

*26th Nov 2019*

* [ ] I'd like the event to be on the public calendar
* [x] It's a repeating event, I would like to have access to the calender to do things on my own

## Support

* [ ] I need coaching or help to get started faster
* [ ] I would like to be introduced to fellow meetup organizers in my area
* [ ] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [ ] I need additional help promoting my event

* [ ] I'd like to have swag (e.g. stickers)

If you're interested in obtaining stickers and/or swag, please send a short email to [the community team](mailto:community@rust-lang.org?subject=[SWAG]), providing

- Your physical mail address and phone number
- The projected number of attendees for your event
- How many events you're planning to run in the future
- Optionally, if you're interested in a certain type of swag for specific reasons (e.g. you're running a T-Shirt give away)

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [ ] We use a Code of Conduct
* [ ] We need a recommendation for one

## Contact details

* [ ] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by flaki** [comment]
Hey @jamessandy !
I'm closing this issue to clean up the repo, but if you have any thoughts or comments (or links/blogposts etc.) to share about how the event went we would be happy to hear about them!
