### ISSUE TITLE
Edinburgh Scotland March Lightning Talks

### ISSUE THREAD

**Issue by mikemoraned** [rust-community/events-team#65]
# New Meetup

## Where

Edinburgh, Scotland, United Kingdom

## What

The aim of this evening is to bring together the Rust community in Edinburgh and nearby, and to illustrate the variety of things that can be done with Rust.

This is for beginners, experts, and everyone in-between.

* [ ] Learners Group
* [x] Meetup with talks
* [ ] Conference/Camp

Links: https://www.meetup.com/rust-edi/events/267810816/*

## When

Thursday 26th March

* [x] I'd like the event to be on the public calendar
* [ ] It's a repeating event, I would like to have access to the calender to do things on my own

## Support

* [ ] I need coaching or help to get started faster
* [x] I would like to be introduced to fellow meetup organizers in my area
* [x] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [ ] I need additional help promoting my event

* [x] I'd like to have swag (e.g. stickers)

(email sent for T-shirt swag)

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [x] We use a Code of Conduct
* [ ] We need a recommendation for one

## Contact details

* [x] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by badboy** [comment]
Added the event to the calendar. I also did answer the email, unfortunately we don't have any swag to sent out.
