### ISSUE TITLE
Belgrade Rust Meetup, first meeting on 11/11/2021!

### ISSUE THREAD

**Issue by nsabovic** [rust-community/events-team#68]
***Please help us by filling out the text below. All answers are optional***

# New Meetup

## Where

Belgrade, Serbia
Location TBD

## What

*A short description of the event.*

* [x] Learners Group
* [x] Meetup with talks
* [ ] Conference/Camp

Links: *add links, e.g. a meetup page, here*

https://www.meetup.com/belgrade-rust-meetup-group/events/281523208/

## When

11-11-2021 at 7pm CET

* [x] I'd like the event to be on the public calendar
* [ ] It's a repeating event, I would like to have access to the calender to do things on my own

## Support

* [x] I need coaching or help to get started faster
* [x] I would like to be introduced to fellow meetup organizers in my area
* [x] I need help promoting

You can promote your event by advertising it on Twitter, Reddit and other channels. We understand that the breadth of this may be overwhelming for organizers and would offer to advertise the event for you. If you already have an active Twitter account and/or regularly announce your meetup through other channels you might not need this option.

* [x] I need additional help promoting my event

## CoC

The Rust project uses a [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) and we generally recommend you to as well. We also give advice on motivations and which one could be fitting for your project.

* [x] We use a Code of Conduct
* [ ] We need a recommendation for one

## Contact details

* [x] I filled out the form at https://docs.google.com/forms/d/e/1FAIpQLSf52YXGhqBaHtCXtVna4iHYMK7IQaTqUW6V-ztsZC8C2TBInQ/viewform and would like you to contact me with news.

**Comment by badboy** [comment]
Hey,

I just added the event to the calendar. This will make it show up in the weekly [This Week in Rust](https://this-week-in-rust.org/) newsletter as well.

It looks like you already have some plans for the first meetup and that's awesome.
